version: '3.8'
services:
  bff:
    build: .
    image: weixiangchen/bff
    container_name: bff
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '7001:7001'
